import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@styles/globals.scss';
import Header from '@components/Header';
import Footer from '@components/Footer';
import styles from './layout.module.scss';
import classNames from 'classnames/bind';
import FloatingButton from '../components/FloatingButton';
import BottomNavigation from '../components/BottomNavigation';

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cx(inter.className, styles.body)}>
        <Header />
        <section>{children}</section>
        <Footer className={styles.footer} />
        <FloatingButton className={styles.footer} />
        <BottomNavigation className={styles.footer} />
      </body>
    </html>
  );
}
